### ISSUE TITLE
"Not a git repository" when trying `contrib install`

### ISSUE THREAD

**Issue by H1D** [contrib/contrib#12]
Am I doing it wrong?
```bash
contrib install videojs/video.js


EXECUTING install

STEP 1. Get all git branches
$ git fetch origin

fatal: Not a git repository (or any of the parent directories): .git
>> FAILED ON STEP 1. Fix any issues and then run "contrib install --begin 1" to continue.
>> exec failed
```

**Comment by heff** [comment]
No, it's just that the video.js contrib.json hadn't been updated to support the new `contrib install` function. Just updated it, can you try it again?

**Comment by H1D** [comment]
It works now.
Thought videojs get all newest `contrib` features first among others =)

**Comment by heff** [comment]
Great! Usually it does. :) Install was built first for repos that have no contrib.json though.
