### ISSUE TITLE
Can't install from NPM with Node version 0.12.2

### ISSUE THREAD

**Issue by SeanDunford** [contrib/contrib#23]
Can't install from NPM with Node version 0.12.2

node --version 0.12.2
npm -v 2.7.5

Tried to run npm install contrib --global and got the following. Looks like you are using some deprecated NAN features that are no longer in the latest stable version of Node. (And likely not in io.js) 

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/nodeproxy/src/node-proxy.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/contrib/node_modules/node-proxy
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "contrib" "--global"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-proxy@0.8.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-proxy@0.8.0 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the node-proxy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-proxy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/seandunford/knotch/api/knotch/npm-debug.log
jarvis:knotch seandunford$ 
```

**Comment by SeanDunford** [comment]
It looks like you are using 

v0.8.0 node-proxy 
https://github.com/samshull/node-proxy/blob/v0.8.0/package.json


which is using a very outdated version of NAN. 0.8 uses NAN version 
        "nan"              : "0.8.x"

and Current nan version is 
1.8.4 
https://github.com/nodejs/nan

**Comment by heff** [comment]
Man, bummer. 0.12 is the version where we can start using execSync. Thanks for figuring it out. Any chance you want to throw together a pull request for it?

**Comment by SeanDunford** [comment]
I attempted to but I'm having issues understanding how to run the project from source. Details on that and how to contribute to this project would be nice to have in the wiki or Readme. 

It's kind of funny because if contrib worked i could use that to help me contrib to contrib. 
![](http://fc02.deviantart.net/fs70/f/2012/220/5/e/xzibit_yo_dawg_render_by_kernelpanicx-d5aa710.png)




I forked the project. Updated package.json. Npm installed. Then I tried to run node ./bin/contrib test
and I am getting these errors. 



jarvis:contrib seandunford$ node bin/contrib test

EXECUTING test

STEP 1. 
$ grunt test

Running "jshint:gruntfile" (jshint) task
>> 1 file lint free.

Running "jshint:lib" (jshint) task
>> 11 files lint free.

Running "jshint:test" (jshint) task
>> 7 files lint free.

Running "nodeunit:files" (nodeunit) task
Testing command_test.js.....OK
Testing config_test.jsFF
>> config_test - no config or init command
>> TypeError: argument at index 2 is not a function: undefined
>> at callCallback (node_modules/sinon/lib/sinon/stub.js:132:23)
>> at Object.functionStub (node_modules/sinon/lib/sinon/stub.js:170:21)
>> at Function.invoke (node_modules/sinon/lib/sinon/spy.js:342:55)
>> at Object.proxy [as confirm] (node_modules/sinon/lib/sinon/spy.js:271:26)
>> at Object.config.confirmCreate (lib/config.js:31:10)
>> at contrib (lib/contrib.js:106:21)
>> at Object.exports.config_test.no config or init command (test/config_test.js:47:5)

>> config_test - config init
>> Message: config is written out
>> Error: false == true
>> at Object.exports.config_test.config init (test/config_test.js:75:10)
>> at Object.exports.config_test.setUp (test/config_test.js:36:5)

>> config_test - config init
>> Message: user is notified that config was written
>> Error: false == true
>> at Object.exports.config_test.config init (test/config_test.js:76:10)
>> at Object.exports.config_test.setUp (test/config_test.js:36:5)

>> config_test - config init
>> Message: an error is logged if a config already exists
>> Error: false == true
>> at Object.exports.config_test.config init (test/config_test.js:81:10)
>> at Object.exports.config_test.setUp (test/config_test.js:36:5)

Testing help_test.js..OK
Testing prompt_test.js..OK
Testing step_test.jsF....
>> command_test - step defined with an object
>> TypeError: undefined is not a function
>> at Object.exports.command_test.tearDown (test/step_test.js:50:17)

Warning: 5/42 assertions failed (227ms) Use --force to continue.

Aborted due to warnings.
>> FAILED ON STEP 1. Fix any issues and then run "contrib test --begin 1" to continue.
>> ExecError: Exec failed

/Users/seandunford/GitProjects/contrib/lib/contrib.js:138
      throw err;
            ^
ExecError: Exec failed
    at ChildProcess.<anonymous> (/Users/seandunford/GitProjects/contrib/lib/exec.js:120:25)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by mmcc** [comment]
> It's kind of funny because if contrib worked i could use that to help me contrib to contrib.

Just popping in to say, I cracked up when I saw the picture and read that line in my email. Also added code fences around your bash output for readability.

**Comment by heff** [comment]
Yeah, the errors look like it's because we've had some architecture changes recently and didn't update the tests to match... I appreciate the attempt at least. I might have some time tonight to clean up the tests.

**Comment by SeanDunford** [comment]
@mmcc  Hah, thanks. I'm here to entertain. 

@heff Cool. Using node/bin/config after updating package.json seems to work with but not entirely sure how stable it is.

**Comment by SeanDunford** [comment]
Is there a possible ETA on this? Was hoping to moving from deprecated contrib-flow to contrib soon.

**Comment by gkatsev** [comment]
Looks like node-proxy updated to a newer NAN, so, updating the dep should fix these issues.
